import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import HomePage from "./homePage";
import Navbar from "../components/Navbar";
import Services from "./services";
import Works from "./works";
import Clients from "./clients";
import Contact from "./contact";
import Footer from "../components/Footer";
import RiwayatPekerjaan from "./pekerjaan";
import ThemeSwitcher from "./themeswitcher";


export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>PortFolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/pro.ico" />
				<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
				<span className="material-icons">color_lens</span>


			</Head>
			<Navbar />
			<ThemeSwitcher /> 
			<HomePage />
			<Services />
			<RiwayatPekerjaan />
			<Works />
			<Clients />
			<Contact />
			<Footer />
			
		</div>
	);
}
